version = 0.1

[dev.deploy.parameters]
stack_name = "timtro-mcp-iam-dev"
region = "ap-southeast-1"
capabilities = ["CAPABILITY_NAMED_IAM"]
no_fail_on_empty_changeset = true
resolve_s3 = true

[prod.deploy.parameters]
stack_name = "timtro-mcp-iam-prod"
region = "ap-southeast-1"
capabilities = ["CAPABILITY_NAMED_IAM"]
no_fail_on_empty_changeset = true
resolve_s3 = true
confirm_changeset = false
